blank_issues_enabled: true
contact_links:
  - name: ğŸ‘¨ğŸ»â€ğŸ’» Robotology Community
    url: https://github.com/robotology/community/discussions
    about: For general discussions on the ecosystem
