# Project information
site_name: 'assistive-rehab'
site_description: 'A framework for developing the assistive intelligence of R1 for clinical rehabilitation.'
site_author: 'Valentina vasco'
site_url: 'https://github.com/robotology/assistive-rehab'

# Repository
repo_name: robotology/assistive-rehab
repo_url: 'https://github.com/robotology/assistive-rehab'
edit_uri: 'edit/master/doc/mkdocs/data'

# Configuration
docs_dir: 'data'
theme:
    name: 'material'
    palette:
        # primary: blue grey
        accent: amber
    features:
        - tabs
    icon:
        logo: material/robot

# Copyright
copyright: 'Copyright &copy; 2019 Istituto Italiano di Tecnologia - iCub Tech'

# Extensions
markdown_extensions:
    - markdown.extensions.admonition
    # - markdown.extensions.codehilite
    - pymdownx.arithmatex
    - pymdownx.betterem:
        smart_enable: all
    - pymdownx.caret
    - pymdownx.critic
    - pymdownx.details
    - pymdownx.inlinehilite
    - pymdownx.highlight
    - pymdownx.keys
    - pymdownx.magiclink:
        user: robotology
        repo: assistive-rehab
        repo_url_shortener: true
        repo_url_shorthand: true
    - pymdownx.mark
    - pymdownx.smartsymbols
    - pymdownx.superfences
    - pymdownx.tasklist
    - pymdownx.tilde
    - markdown.extensions.toc:
        permalink: true

# Page tree
nav:
    - Home: 'index.md'
    - News:
        - Latest: 'latest_news.md'
    - Install: 'install.md'
    - Documentation [v0.6.0]: https://robotology.github.io/assistive-rehab/doc/doxygen/doc/html/index.html
    - Tutorials:
        - Getting started: 'tutorial_intro.md'
        - How to manage a skeleton object: 'create_new_skeleton.md'
        - How to replay an experiment: 'replay_an_experiment.md'
        - How to run the pipeline in a disembodied manner: 'disembodied.md'
        - How to temporally align two signals: 'align_signals.md'
        - How to run the rehabilitation demos: 'main_apps.md'
        - How to run the virtual demo: 'virtual_demo.md'
        - How to detect the TUG lines: 'tug_lines.md'
        - How to run the TUG demo: 'tug_demo.md'
        - How to use the gazebo plugin: 'gazebo_plugin.md'
        - How to configure the wifi button: 'wifi_button.md'
    - Milestones:
        - Y1M5: 'Y1M5.md'
        - Y1Q3: 'Y1Q3.md'
        - Comparison between Y1Q3 and Y1M5: 'comparison_releases.md'
        - TUG: 'TUG.md'
    - About: 'about.md'
    - License: 'license.md'
